### ISSUE TITLE
CWD攻撃に対する脆弱性

### ISSUE THREAD

**Issue by udaken** [yak1ex/axpdfium#2]
はじめまして。

あるSusieプラグイン対応アプリケーションを調査していたところ、
カレントディレクトリのicudt.dllを読み込む挙動をしました。
(procmon.exeのログと、実際にダミーのDLLを配置して確認)

調べたところ、axpdfiumからicudt.dllを読み込んでいるようでした。
(ソースは調査していませんが、バイナリに"icudt.dll"が含まれていることから断定させて頂きます。)

元のpdfiumに由来する挙動だと思いますが、
何らかの対応が必要だと考えます。
axpdfium側で対策を行うか、利用者に注意喚起(場合によっては公開停止等)が必要では無いでしょうか？

**Comment by udaken** [comment]
補足させていただきます。

DLLのロードディレクトリの設定は基本的にはアプリケーション側の責務だと考えていますが、
axpdfiumの問題は「通常存在しないDLLをロードしようとする」ことです。

**Comment by yak1ex** [comment]
指摘ありがとうございます。以下のように対処するつもりです。

1. さしあたってサイト上に注意書きの追加
2. pdfium を更新して動作確認
同様の挙動は恐らく pdfium のベースになっている chromium 時点から存在しているのではないかと思いますが、少なくとも Chromium に関しては DLL loading 関連の修正に積極的ではないように見えるので改善されるかは不明です。
    - https://bugs.chromium.org/p/chromium/issues/detail?id=691975
    - https://dev.chromium.org/Home/chromium-security/security-faq#TOC-Why-aren-t-physically-local-attacks-in-Chrome-s-threat-model-
3. ↑で改善しない場合、plugin ロード時に SetDllDirectory() 呼び出し
動的ロードのタイミング次第ですが pdfium の初期化前に SetDllDirectory("") を呼べば回避できると考えています。

**Comment by udaken** [comment]
承知しました。対応をお待ちしてます。
(バグ情報はこちらにしか記載してません。)

> SetDllDirectory("") を呼べば

弊害が発生するアプリケーションもあるかもしれませんが、やむなしですね。

**Comment by yak1ex** [comment]
1年以上も放置して申し訳ありませんでした。
PDFiumを更新し不要な機能(JS等)を無効化して使用することで該当DLLのロード自体がなくなりました。
v0.02 としてリリースしました。http://yak3.myhome.cx:8080/junks/index.html#misc.axpdfium_spi
